using Microsoft.Playwright;
using MT.Uptime.Core.Domain;
using MT.Uptime.Tests.E2E.Support;

namespace MT.Uptime.Tests.E2E.Ui;

/// <summary>
/// U1, U3 and U11 — signing in, creating one monitor of every type through the real form, and
/// editing and deleting one.
/// <para>
/// U3 is the reason this tier exists at all. Tier 2 seeds monitors straight into the database and
/// calls the scheduler, which proves the engine works and proves nothing about the editor: a form that
/// wrote the wrong JSON, dropped a field on a type switch, or silently failed validation would leave
/// every seeded test green and every real monitor broken.
/// </para>
/// </summary>
public class MonitorsUiTests : IClassFixture<UiFixture>
{
    private readonly UiFixture _fx;

    public MonitorsUiTests(UiFixture fx) => _fx = fx;

    [UIFact]
    public async Task U1_signing_in_reaches_a_live_dashboard()
    {
        await _fx.StartAsync();
        var page = await _fx.SignInAsync();

        await Assertions.Expect(page.GetByRole(AriaRole.Link, new() { Name = "+ New monitor" })).ToBeVisibleAsync();

        // "The circuit is alive" is the assertion that matters, and it is not the same as "the page
        // rendered". Blazor Server sends the first render over plain HTTP and only then negotiates a
        // WebSocket; a broken circuit produces a page that looks perfect and responds to nothing.
        // Everything in this tier after this point depends on that connection existing.
        await page.WaitForFunctionAsync(
            "() => window.Blazor !== undefined",
            null,
            new PageWaitForFunctionOptions { Timeout = 20_000 });
    }

    [UITheory]
    [InlineData(MonitorType.Http)]
    [InlineData(MonitorType.Tcp)]
    [InlineData(MonitorType.Dns)]
    [InlineData(MonitorType.MySql)]
    [InlineData(MonitorType.Postgres)]
    [InlineData(MonitorType.Tls)]
    public async Task U3_a_monitor_created_through_the_form_goes_Up(MonitorType type)
    {
        // Every actively-probed type, created the way a person creates one: pick the type, fill in what
        // the form asks for, save, and watch the dashboard.
        //
        // Push is excluded here and tested separately below, because it is the one type that cannot go
        // Up on its own — something has to ping it first.
        await _fx.StartAsync();
        var page = await _fx.SignInAsync();

        var name = $"u3-{type}-{Guid.NewGuid():N}"[..20];
        await MonitorForm.CreateAsync(page, type, name);

        await Assertions.Expect(page.GetByRole(AriaRole.Link, new() { Name = name })).ToBeVisibleAsync();
        await MonitorForm.WaitForStatusAsync(page, name, "Up");

        await DeleteMonitorAsync(page, name);
    }

    [UIFact]
    public async Task U3_a_push_monitor_goes_Up_when_its_ping_URL_is_called()
    {
        await _fx.StartAsync();
        var page = await _fx.SignInAsync();

        var name = $"u3-push-{Guid.NewGuid():N}"[..18];
        await MonitorForm.BeginAsync(page, MonitorType.Push, name);

        // The token is generated by the editor and shown read-only. Reading it here is not a shortcut
        // around the product — it is the only way an operator gets it either.
        var pingUrl = await MonitorForm.PushPingUrlAsync(page);
        Assert.Contains("/ping/", pingUrl, StringComparison.Ordinal);

        await MonitorForm.SaveAsync(page);

        using var client = new HttpClient();
        var ping = await client.GetAsync(pingUrl);
        Assert.True(ping.IsSuccessStatusCode, $"the ping URL from the form answered {(int)ping.StatusCode}");

        await MonitorForm.WaitForStatusAsync(page, name, "Up");

        await DeleteMonitorAsync(page, name);
    }

    [UIFact]
    public async Task U11_a_monitor_can_be_edited_and_deleted()
    {
        await _fx.StartAsync();
        var page = await _fx.SignInAsync();

        var name = $"u11-{Guid.NewGuid():N}"[..16];
        await MonitorForm.CreateAsync(page, MonitorType.Tcp, name);
        await MonitorForm.WaitForStatusAsync(page, name, "Up");

        // Edit: change the interval and confirm it survives a round trip through the database rather
        // than merely sticking in the component's model.
        await page.Locator("tr", new() { HasText = name }).GetByRole(AriaRole.Link, new() { Name = "Edit" }).ClickAsync();
        await page.GetByLabel("Interval (s)", new() { Exact = true }).FillAsync("30");
        await MonitorForm.SaveAsync(page);

        await page.Locator("tr", new() { HasText = name }).GetByRole(AriaRole.Link, new() { Name = "Edit" }).ClickAsync();
        await Assertions.Expect(page.GetByLabel("Interval (s)", new() { Exact = true })).ToHaveValueAsync("30");

        await page.GotoAsync("/");
        await DeleteMonitorAsync(page, name);

        // Gone from the dashboard, and gone for good: a reload is what distinguishes a row removed
        // from the component's list from a row removed from the database.
        await page.ReloadAsync();
        await Assertions.Expect(page.GetByRole(AriaRole.Link, new() { Name = name })).ToHaveCountAsync(0);
    }

    /// <summary>
    /// Removes a monitor through the editor's own Delete button, accepting the confirmation.
    /// <para>
    /// Every test here cleans up after itself, and on this tier that is not tidiness. Tier 3 runs
    /// against the <b>installed</b> instance, whose database survives the test run — so a monitor left
    /// behind is probed forever, appears in the next run's dashboard assertions, and joins the next
    /// correlated incident.
    /// </para>
    /// </summary>
    internal static async Task DeleteMonitorAsync(IPage page, string name)
    {
        page.Dialog += async (_, dialog) => await dialog.AcceptAsync();

        await page.GotoAsync("/");
        var row = page.Locator("tr", new() { HasText = name });
        if (await row.CountAsync() == 0) return;

        await row.GetByRole(AriaRole.Link, new() { Name = "Edit" }).First.ClickAsync();
        await page.GetByRole(AriaRole.Button, new() { Name = "Delete", Exact = true }).ClickAsync();
        await page.WaitForURLAsync(u => !u.Contains("/edit", StringComparison.Ordinal));
    }
}
