// <auto-generated />
using System;
using MT.Uptime.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MT.Uptime.Core.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814193613_AddDegradedAndUserProfile")]
    partial class AddDegradedAndUserProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MT.Uptime.Core.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordResetExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.Heartbeat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Important")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonitorId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ResponseTimeMs")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonitorId", "Timestamp");

                    b.ToTable("Heartbeats");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.Monitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CertExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DegradedAfterChecks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHeartbeatAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LastResponseTimeMs")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResendEveryN")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SlowThresholdMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UpsideDown")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.ToTable("Monitors");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.MonitorEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonitorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MonitorId", "StartedAt");

                    b.ToTable("MonitorEvents");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.MonitorNotification", b =>
                {
                    b.Property<int>("MonitorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotificationChannelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MonitorId", "NotificationChannelId");

                    b.HasIndex("NotificationChannelId");

                    b.ToTable("MonitorNotifications");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.NotificationChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NotificationChannels");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.StatRollup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BucketStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("DegradedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DownCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonitorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PendingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PingAvgMs")
                        .HasColumnType("REAL");

                    b.Property<double?>("PingMaxMs")
                        .HasColumnType("REAL");

                    b.Property<double?>("PingMinMs")
                        .HasColumnType("REAL");

                    b.Property<int>("UpCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MonitorId", "Period", "BucketStart")
                        .IsUnique();

                    b.ToTable("StatRollups");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.StatusPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Published")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("StatusPages");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.StatusPageMonitor", b =>
                {
                    b.Property<int>("StatusPageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonitorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("StatusPageId", "MonitorId");

                    b.HasIndex("MonitorId");

                    b.ToTable("StatusPageMonitors");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.Heartbeat", b =>
                {
                    b.HasOne("MT.Uptime.Core.Domain.Monitor", "Monitor")
                        .WithMany("Heartbeats")
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitor");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.MonitorEvent", b =>
                {
                    b.HasOne("MT.Uptime.Core.Domain.Monitor", "Monitor")
                        .WithMany("Events")
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitor");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.MonitorNotification", b =>
                {
                    b.HasOne("MT.Uptime.Core.Domain.Monitor", "Monitor")
                        .WithMany("Notifications")
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MT.Uptime.Core.Domain.NotificationChannel", "NotificationChannel")
                        .WithMany("Monitors")
                        .HasForeignKey("NotificationChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitor");

                    b.Navigation("NotificationChannel");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.StatRollup", b =>
                {
                    b.HasOne("MT.Uptime.Core.Domain.Monitor", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitor");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.StatusPageMonitor", b =>
                {
                    b.HasOne("MT.Uptime.Core.Domain.Monitor", "Monitor")
                        .WithMany("StatusPageLinks")
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MT.Uptime.Core.Domain.StatusPage", "StatusPage")
                        .WithMany("Monitors")
                        .HasForeignKey("StatusPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitor");

                    b.Navigation("StatusPage");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.Monitor", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Heartbeats");

                    b.Navigation("Notifications");

                    b.Navigation("StatusPageLinks");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.NotificationChannel", b =>
                {
                    b.Navigation("Monitors");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.StatusPage", b =>
                {
                    b.Navigation("Monitors");
                });
#pragma warning restore 612, 618
        }
    }
}
