// <auto-generated />
using System;
using MT.Uptime.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MT.Uptime.Core.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MT.Uptime.Core.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordResetExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionStamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.Heartbeat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Important")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Maintenance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonitorId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ResponseTimeMs")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonitorId", "Timestamp");

                    b.ToTable("Heartbeats");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.Incident", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AcknowledgedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationKey")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastEventAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonitorCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Published")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SnoozedUntil")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AcknowledgedByUserId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("CorrelationKey", "ResolvedAt");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.IncidentUpdate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("IncidentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PostedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostedByUserId");

                    b.HasIndex("IncidentId", "PostedAt");

                    b.ToTable("IncidentUpdates");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.MaintenanceWindow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AppliesToAllMonitors")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaysOfWeekMask")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Publish")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Recurrence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartMinuteOfDay")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.ToTable("MaintenanceWindows");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.MaintenanceWindowMonitor", b =>
                {
                    b.Property<int>("MaintenanceWindowId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonitorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaintenanceWindowId", "MonitorId");

                    b.HasIndex("MonitorId");

                    b.ToTable("MaintenanceWindowMonitors");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.MaintenanceWindowTag", b =>
                {
                    b.Property<int>("MaintenanceWindowId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaintenanceWindowId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("MaintenanceWindowTags");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.Monitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CertExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DegradedAfterChecks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHeartbeatAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LastResponseTimeMs")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResendEveryN")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SlowThresholdMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UpsideDown")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.ToTable("Monitors");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.MonitorEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IncidentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonitorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("MonitorId", "StartedAt");

                    b.ToTable("MonitorEvents");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.MonitorNotification", b =>
                {
                    b.Property<int>("MonitorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotificationChannelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MonitorId", "NotificationChannelId");

                    b.HasIndex("NotificationChannelId");

                    b.ToTable("MonitorNotifications");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.MonitorTag", b =>
                {
                    b.Property<int>("MonitorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MonitorId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("MonitorTags");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.NotificationChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NotificationChannels");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.StatRollup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BucketStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("DegradedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DownCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaintenanceCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonitorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PendingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PingAvgMs")
                        .HasColumnType("REAL");

                    b.Property<double?>("PingMaxMs")
                        .HasColumnType("REAL");

                    b.Property<double?>("PingMinMs")
                        .HasColumnType("REAL");

                    b.Property<int>("UpCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MonitorId", "Period", "BucketStart")
                        .IsUnique();

                    b.ToTable("StatRollups");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.StatusPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Published")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("StatusPages");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.StatusPageMonitor", b =>
                {
                    b.Property<int>("StatusPageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonitorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("StatusPageId", "MonitorId");

                    b.HasIndex("MonitorId");

                    b.ToTable("StatusPageMonitors");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.Heartbeat", b =>
                {
                    b.HasOne("MT.Uptime.Core.Domain.Monitor", "Monitor")
                        .WithMany("Heartbeats")
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitor");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.Incident", b =>
                {
                    b.HasOne("MT.Uptime.Core.Domain.AppUser", "AcknowledgedBy")
                        .WithMany()
                        .HasForeignKey("AcknowledgedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AcknowledgedBy");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.IncidentUpdate", b =>
                {
                    b.HasOne("MT.Uptime.Core.Domain.Incident", "Incident")
                        .WithMany("Updates")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MT.Uptime.Core.Domain.AppUser", "PostedBy")
                        .WithMany()
                        .HasForeignKey("PostedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Incident");

                    b.Navigation("PostedBy");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.MaintenanceWindowMonitor", b =>
                {
                    b.HasOne("MT.Uptime.Core.Domain.MaintenanceWindow", "MaintenanceWindow")
                        .WithMany("Monitors")
                        .HasForeignKey("MaintenanceWindowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MT.Uptime.Core.Domain.Monitor", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaintenanceWindow");

                    b.Navigation("Monitor");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.MaintenanceWindowTag", b =>
                {
                    b.HasOne("MT.Uptime.Core.Domain.MaintenanceWindow", "MaintenanceWindow")
                        .WithMany("Tags")
                        .HasForeignKey("MaintenanceWindowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MT.Uptime.Core.Domain.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaintenanceWindow");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.MonitorEvent", b =>
                {
                    b.HasOne("MT.Uptime.Core.Domain.Incident", "Incident")
                        .WithMany("Events")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MT.Uptime.Core.Domain.Monitor", "Monitor")
                        .WithMany("Events")
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("Monitor");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.MonitorNotification", b =>
                {
                    b.HasOne("MT.Uptime.Core.Domain.Monitor", "Monitor")
                        .WithMany("Notifications")
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MT.Uptime.Core.Domain.NotificationChannel", "NotificationChannel")
                        .WithMany("Monitors")
                        .HasForeignKey("NotificationChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitor");

                    b.Navigation("NotificationChannel");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.MonitorTag", b =>
                {
                    b.HasOne("MT.Uptime.Core.Domain.Monitor", "Monitor")
                        .WithMany("Tags")
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MT.Uptime.Core.Domain.Tag", "Tag")
                        .WithMany("Monitors")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitor");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.StatRollup", b =>
                {
                    b.HasOne("MT.Uptime.Core.Domain.Monitor", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitor");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.StatusPageMonitor", b =>
                {
                    b.HasOne("MT.Uptime.Core.Domain.Monitor", "Monitor")
                        .WithMany("StatusPageLinks")
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MT.Uptime.Core.Domain.StatusPage", "StatusPage")
                        .WithMany("Monitors")
                        .HasForeignKey("StatusPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitor");

                    b.Navigation("StatusPage");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.Incident", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Updates");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.MaintenanceWindow", b =>
                {
                    b.Navigation("Monitors");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.Monitor", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Heartbeats");

                    b.Navigation("Notifications");

                    b.Navigation("StatusPageLinks");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.NotificationChannel", b =>
                {
                    b.Navigation("Monitors");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.StatusPage", b =>
                {
                    b.Navigation("Monitors");
                });

            modelBuilder.Entity("MT.Uptime.Core.Domain.Tag", b =>
                {
                    b.Navigation("Monitors");
                });
#pragma warning restore 612, 618
        }
    }
}
